"""Bundle the question banks into flashcards/question-banks.js so the web app
can auto-load them when opened directly (file://), with no server required.

Banks are organized by Splunk certification. The four SPLK-2002 source files
(practice test + 3 quizzes) overlap heavily, so they are merged and de-duped
into a single Architect bank at build time. Source files are never modified.

Run this whenever you add or regenerate a bank:
    python build_banks.py
"""
import json
import os

# Certification banks: display label -> ordered list of source files.
# Duplicate questions (by text) across sources are merged into one entry.
BANK_SPECS = [
    {"label": "Power User (SPLK-1002)", "sources": ["questions/poweruser1002.json"]},
    {"label": "Admin (SPLK-1003)",      "sources": ["questions/admin1003.json"]},
    {"label": "Architect (SPLK-2002)",  "sources": [
        "questions/2002_practice_test.json",
        "questions/2002_quiz_1.json",
        "questions/2002_quiz_2.json",
        "questions/2002_quiz_3.json",
        "flashcards/questions.json",
    ]},
]
DEFAULT_LABEL = "Architect (SPLK-2002)"


def load(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def merge_sources(sources):
    """Concatenate sources, de-duping by question text. When the same question
    appears more than once, keep the first but enrich it: fill an empty
    explanation from a later copy and union their resource links."""
    by_key = {}
    order = []
    for path in sources:
        if not os.path.exists(path):
            print(f"  WARNING: missing source {path}")
            continue
        data = load(path)
        if not isinstance(data, list):
            print(f"  WARNING: {path} is not a list; skipping")
            continue
        for q in data:
            key = q.get("question", "").strip()
            if not key:
                continue
            if key not in by_key:
                by_key[key] = json.loads(json.dumps(q))  # deep copy
                order.append(key)
            else:
                existing = by_key[key]
                if not (existing.get("explanation") or "").strip() and (q.get("explanation") or "").strip():
                    existing["explanation"] = q["explanation"]
                merged = list(existing.get("resources") or [])
                for url in (q.get("resources") or []):
                    if url not in merged:
                        merged.append(url)
                if merged:
                    existing["resources"] = merged
    return [by_key[k] for k in order]


def main():
    banks = {}
    for spec in BANK_SPECS:
        merged = merge_sources(spec["sources"])
        if not merged:
            print(f"  (skipped {spec['label']}: no questions)")
            continue
        banks[spec["label"]] = merged
        raw = sum(len(load(s)) for s in spec["sources"] if os.path.exists(s))
        extra = f"  (merged from {raw})" if raw != len(merged) else ""
        print(f"  + {spec['label']}: {len(merged)} questions{extra}")

    if not banks:
        print("No banks built. Nothing written.")
        return

    default_label = DEFAULT_LABEL if DEFAULT_LABEL in banks else next(iter(banks))

    out_path = os.path.join("flashcards", "question-banks.js")
    os.makedirs("flashcards", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_banks.py — do not edit by hand.\n")
        f.write("window.QUESTION_BANKS = ")
        json.dump(banks, f, ensure_ascii=False, indent=2)
        f.write(";\n")
        f.write(f"window.DEFAULT_BANK = {json.dumps(default_label)};\n")

    total = sum(len(v) for v in banks.values())
    print(f"\nWrote {len(banks)} banks ({total} questions) to {out_path}")
    print(f"Default bank: {default_label}")


if __name__ == "__main__":
    main()
