import random


# Complete Q/A pairs
qa_pairs = [
    ("What is the only writeable bucket type?", "Hot bucket"),
    ("By what filter are indexes divided into buckets?", "By time"),
    ("What are the 4 types of searches in Splunk (by performance)?", "Dense, Sparse, Super Sparse, Rare"),
    ("In searches, what is the scanCount?", "The number of events scanned for that particular search"),
    ("What are the requirement of the underlying search in order to get multi-series table?", "The underlying search must use reporting search commands like chart or timechart"),
    ("What are the seven chart types?", "Line, Area, Column, Bar, Bubble, Scatter and Pie"),
    ("What is a trait of scatter charts?", "Can only show two dimensions. Shows trends in the relationship between discrete data values"),
    ("What is a trait of bubble charts?", "Provides a visual way to view a three dimensional series"),
    ("What are two commonly used clauses for chart?", "over and by"),
    ("What does the over and by clauses do when used with chart?", "divides the data into sub-groupings"),
    ("True/False: You can only split chart results over two dimensions", "True"),
    ("chart and timechart commands automatically filter results to include how many values?", "10"),
    ("What happens to surplus resulting values of chart and timechart commands?", "They are grouped into other"),
    ("True/False: Null values are not shown by default by chart and timechart", "False"),
    ("What is always the value on the x-axis for timechart?", "_time"),
    ("True/False: Functions and arguments used with stats and chart can not be used with timechart", "False"),
    ("True/False: As with chart, it is possible to split timechart by two fields", "False. It is only possible to split by one field"),
    ("What is the argument for adjusting sampling interval of timechart?", "span"),
    ("What does the trendline command do?", "allows you to overlay a computed moving average on a chart"),
    ("What is the syntax of the trendline command?", "trendline <trendtype><period>(field) [AS newfield]"),
    ("What command can be used to look up and add location information to an event?", "iplocation"),
    ("What information does the iplocation command include?", "city, country, region, latitude and longitude"),
    ("What is the data-requirement for the geostats command?", "Data must include latitude and longitude values"),
    ("These arguments are used to control column counts when using the geostats command", "globallimit and locallimit"),
    ("This command is used to compute statistical functions and render a cluster map", "geostats"),
    ("What command can be used to show relative metrics for predefined geographic regions?", "geom"),
    ("True/False: A sparkline is an inline chart, that can be added to timechart", "True"),
    ("True/False: Automatically totaling of every columns can be done by using the Format option", "True"),
    ("This command can be used to add total of all or selected fields", "addtotals"),
    ("The row option for addtotals does (if enabled)", "create a column that contains numeric totals for each row"),
    ("The column option for addtotals does (if enabled)", "create a row that contains numeric totals for each column"),
    ("What does the labelfield option for addtotals specify?", "What field the label should be placed in (in general, this should be the leftmost and first field)"),
    ("The eval command can be used to", "perform calculations, convert, round and format values, use conditional statements"),
    ("This command allows you to calculate and manipulate field values in your report", "eval"),
    ("True/false: Results of eval can be written to existing field", "True"),
    ("What happens with a destination field value if the field is the same as the resulting field of the eval command?", "The field value gets overwritten by the resulting value outputted from the eval command"),
    ("True/False: Indexed data get modified after field values are overwritten by the eval command.", "False"),
    ("This operator is used for concatenation", "+"),
    ("This function can be used to set the value of a field to the number of decimals you specify", "round"),
    ("True/False: The tostring function can be used with eval", "True"),
    ("How can you use eval to format numeric field values to strings?", "By adding characters to the field values"),
    ("What separator is used when having multiple expressions used with eval command?", "comma"),
    ("If function used with eval: What is field value of SalesTerritory for a VendorID of 80000 in the following evaluation? | eval SalesTerritory = if((VendorID >= 7000 AND VendorID <8000), 'Asia', 'Rest of the World')", "Rest of the World"),
    ("True/False: The search command treats field values in a case-insensitive manner", "True"),
    ("True/False: The where command treats field values in a case-insensitive manner", "False"),
    ("True/False: Unquoted or single-quoted strings are treated as fields.", "True"),
    ("To be able to do wildcard searches with the where command, this operator must be used", "like"),
    ("What is the fillnull value used for?", "To replace null values in fields. Default replacement value is 0."),
    ("What is a transaction?", "A transaction is any group of related events that span time"),
    ("What is the syntax of the transaction command?", "transaction field-list. field-list argument is a list of one or multiple fields."),
    ("True/False: Transaction command creates a single event from a group of events", "True"),
    ("This field is produced by running the transaction command", "duration - difference between timestamp of first and last event in the transaction"),
    ("What does the maxspan argument do when used for transaction?", "Defines the maximum total time between the earliest and latest events"),
    ("What does the maxpause argument do when used for transaction?", "Specify maximum total time between events."),
    ("What can be said about the events returned from the following search? index=web sourcetype=access_combined | transaction clientip JSESSIONID startswith=eval(action='addtocart') endswith=eval(action='purchase')", "The first event in this transaction includes the action 'addtocart', the last include the action 'purchase'"),
    ("What are the limited number of events per transaction by default?", "1000"),
    ("Why is stats recommended over transaction?", "Faster and more efficient"),
    ("When do you need to use transaction?", "When you need to see events correlated together, and/or must define event grouping based on start/end values or segments on time"),
    ("How can admins change the limit of numbers of events per transaction?", "by configuring max_events_per_bucket in limits.conf"),
    ("What are Knowledge Objects?", "Knowledge objects are tools you use to discover and analyze various aspects of your data"),
    ("True/false: Knowledge Objects are shareable, reusable and searchable", "True"),
    ("True/False: The Power User role can create an object that persists globally across all apps", "False"),
    ("True/False: The Power User role can create an object that persists in the context of a specific app", "True"),
    ("What is the Splunk Common Information Model (CIM)?", "A methodology for normalizing data, easily correlate data from different sources and source type."),
    ("Which meta fields are already stored in the index prior to search time?", "host, source and sourcetype"),
    ("Which internal fields are stored in the index prior to search time?", "_time and _raw"),
    ("At this time, field discovery discovers fields directly related to the search's results", "search time"),
    ("True/False: After extracting fields using the field extractor (FX), it is possible to share the extracted fields.", "True. Extracted fields exists as knowledge objects."),
    ("What are the two methods for doing field extractions?", "Regex and delimiter"),
    ("These knowledge objects provide a way of normalizing data over any default field", "field aliases"),
    ("True/false: Field aliases are applied after field extraction, before lookups", "True"),
    ("True/false: It is not possible to apply field aliases to lookups", "False"),
    ("True/false: Multiple aliases can be applied to one field", "True"),
    ("True/false: After a field alias have been made, the field alias can be used as an ordinary field in SPL", "True"),
    ("What is a calculated field?", "Shortcut for performing repetitive, long, or complex transformations using the eval command"),
    ("What is true about a calculated field?", "Must be based on an extracted field"),
    ("Where can both calculated field and field aliases be set up (using the GUI)?", "Settings->Fields"),
    ("These knowledge objects are like nicknames that are created for related field/value pairs", "Tags"),
    ("True/False: Tags are case sensitive", "True"),
    ("True/False: You can only create one tag for any field/value combination", "False"),
    ("True/False: Knowledge objects like tags, field aliases and calculated fields are searchable", "True"),
    ("How does a tag appear after being selected?", "In the results as tags, in parentheses next to the associated field/value pairs"),
    ("The syntax for searching for a tag associated with a value is?", "tag=<tag name>"),
    ("The syntax for searching for a tag associated with a value on a specific field is?", "tag::<field> = <tagname>"),
    ("Where can tag-settings (including permissions) be edited?", "Settings->Tags-> List by field value pair"),
    ("This knowledge object can be used to group similar types of events", "Event types"),
    ("How do you create an event type?", "Create and execute a search, press 'save as'-> Event types"),
    ("True/False: Event type names can contain spaces", "False"),
    ("Which criteria must be reviewed and refined when using the Event Type Builder?", "Search string, Field values, tags"),
    ("What is the syntax for using eventtypes in a search?", "eventtype=<eventtype_name>"),
    ("At what time does Splunk evaluate the events when searching and using event types in your search?", "Search time"),
    ("How can you tag event types? (GUI)", "Either by using 'Settings-> Event Types' or by using 'Event details->Actions'"),
    ("True/False: It is not possible to add tag to an Event Type", "False"),
    ("True/false: Event Types does not include a time range, while a saved report does", "True"),
    ("These knowledge objects are useful when you frequently run searches or reports with similar search syntax", "macros"),
    ("True/false: Macros are shareable", "True"),
    ("What happens if an event fits in multiple eventtypes?", "Priority decides which event takes precedence in the display order"),
    ("At what time are parameter values passed to macro?", "At execution time"),
    ("How can you create a macro?(GUI)", "Settings->Advanced search-> Search macros"),
    ("What is the syntax for using macros in searches?", "`macro`"),
    ("How do you include the number of arguments to a macro?", "By adding the number in parentheses after the macro name"),
    ("When setting up arguments for macros in the macro definition, with what character must the argument(s) be surrounded by?", "$"),
    ("True/False: This is a valid search: | 'monthly_sales(euro, £, 0.79)'", "False"),
    ("What is the validation expression for macros?", "An expression for each argument to the macro can be made, with a corresponding error message, to ensure that the macro is being used correctly"),
    ("Should macros include leading pipes?", "No, it is not considered best practice, as someone may put a pipe in front of the macro when using it in a search string"),
    ("What is a workflow action?", "Execute workflow actions from an event in your search results to interact with external resources or run another search"),
    ("Which types of workflow actions exist?", "GET, POST, Search"),
    ("What is a Search workflow action?", "A search workflow action uses field values to perform a secondary search"),
    ("What is a POST workflow action?", "A POST workflow action sends field values to an external resource"),
    ("What is a GET workflow action?", "A GET workflow action retrieves information from an external resource"),
    ("How do you create a new Workflow action?", "Settings-> Fields-> Workflow actions-> New workflow action"),
    ("True/False: A workflow action can be applied to both fields and event types.", "True"),
    ("How can workflow actions be tested?", "By pressing event actions on event in the search, and clicking the name of the created Workflow action"),
    ("What is a pivot?", "It's essentially a subset of data based on a data model"),
    ("What is a data model?", "Hierarchically structured datasets that generate searches and drive pivots"),
    ("What three types of datasets can a data model consist of?", "Events, searches and transactions"),
    ("How are datasets saved in pivots?", "Each event, search or transaction is saved as a separate dataset"),
    ("What are constraints when it comes to data model events?", "Constraints are essentially the search broken down into a hierarchy"),
    ("True/false: Data models are hierarchical structures where children datasets inherit constraints and field from their parent dataset(s)", "True"),
    ("What is the benefit of using root events to root transactions and root searches when creating data models?", "Root events can be accelerated, while the others cannot."),
    ("What are constraints for a root event?", "Essentially search terms"),
    ("What methods can be used for adding fields to a data model?", "Auto-extraction, eval expression, lookup, regular expression, Geo IP"),
    ("What are the different field types for a data model?", "String, Number, Boolean, IPV4"),
    ("What are field flags for data models?", "Field flags are used for setting options for how the field should be used and the necessity of the field for events in the pivot driven by the data model"),
    ("What different field flags exist?", "Optional, required, Hidden, Hidden & required"),
    ("What is the use of hidden fields?", "They can be used for fields that are only being used to define another field, such as an eval expression"),
    ("What does the 'Required' Field flag imply?", "Only events that contain this field are returned in Pivot"),
    ("What is the data model name in this search? | pivot Buttercup_Games_Site_Activity failed_request count(failed_request) AS 'Count of Failed requests'", "Buttercup_Games_Site_Activity"),
    ("What is the object name in this search? | pivot Buttercup_Games_Site_Activity failed_request count(failed_request) AS 'Count of Failed requests'", "failed_request"),
    ("What is the split row field in this search? | pivot Buttercup_Games_Site_Activity failed_request count(failed_request) AS 'Count of Failed requests'", "count(failed_request)"),
    ("What are Data Model Search datasets?", "Arbitrary searches that include transforming commands to define the dataset that they represent"),
    ("What fields are available for use by a transaction dataset?", "Fields that have already been added to the model using event or search datasets."),
    ("What is required for a transaction dataset?", "At least one event or search dataset to the data model"),
    ("How can permissions be set for data models?", "Based on Users, or owner, app or all apps"),
    ("How can data models be moved from the test environment to prod environment?", "By uploading/download via the Splunk Web interface"),
    ("How are data models accelerated?", "By creating summaries defined in time-series index files (tsidx) that have been optimized for speed"),
    ("What happens with fields in when accelerating a data model?", "All fields in the model become 'indexed' fields, i.e. they are available in tsidx files."),
    ("True/False: A private data model can be accelerated", "False"),
    ("True/False: Accelerated data models can be edited", "False"),
    ("True/False: Only root events can be accelerated.", "True"),
    ("What is the Common Information Model (CIM)?", "The Splunk Common Information Model provides a methodology to normalize data"),
    ("What are some of the benefits of using the Common Information Model?", "Easier and more efficient correlation of data from different sources and source types"),
    ("When should the CIM be leveraged?", "When creating field extractions, field aliases, event types and tags"),
    ("What are included in the CIM Add-on?", "Set of 22 pre-configured data models, fields and event category tags, least common denominator of a domain of interest"),
    ("True/false: The data models included in the CIM add-on are configured with data model acceleration turned off.", "True"),
    ("How can you use the CIM add-on?", "By going to settings-> Data models, and identify a data model relevant to your dataset"),
    ("What can the CIM add-on be used for?", "Creating new event types, tags, field aliases and field extractions"),
    ("How can you validate that a field extraction is correctly set up according to CIM?", "By using the datamodel command and search against a specified data model object to see that the extracted field exists in the data model"),
    ("True/false: data model name and dataset name are case sensitive", "True"),
    ("What is the data set name in the following search: | datamodel Web Email search | fields Web*", "Email"),
    ("What does the 'from' command do?", "Retrieves data from a data model or named dataset"),
    ("How does the 'from' command differ to the 'datamodel' command?", "Datamodel returns all fields prepended with data model name, from datamodel returns specified fields only"),
    ("True/false: 'from' command can also retrieve data from saved searches, reports or lookup files", "True"),
    ("What is true about event type?", "Event types cannot include pipes or subsearches"),
    ("What does the duration field for transaction mean?", "Difference between timestamp of first and last event in the transaction"),
    ("True/False: Data models from CIM search across all indexes by default", "True")
]

# Function to generate random choices for each question
def generate_choices(correct_answer):
    pool = [
        "Hot bucket", "Warm bucket", "Cold bucket", "Frozen bucket",
        "By source type", "By host", "By time", "By size",
        "Dense, Sparse, Super Sparse, Rare", "Dense, Sparse, Common, Rare",
        "Dense, Normal, Sparse, Rare", "Dense, Sparse, Super Rare, Common",
        "The number of events scanned for that particular search", "The number of events returned by the search",
        "The number of searches run", "The number of buckets scanned",
        "The underlying search must use reporting search commands like chart or timechart", "The search must use stats command",
        "The search must use table command", "The search must use rex command",
        "Line", "Area", "Column", "Bar", "Bubble", "Scatter", "Pie",
        "Can only show two dimensions. Shows trends in the relationship between discrete data values",
        "Provides a visual way to view a three dimensional series",
        "over", "by",
        "divides the data into sub-groupings",
        "True", "False",
        "10", "5", "15", "20",
        "They are grouped into other",
        "_time",
        "span",
        "allows you to overlay a computed moving average on a chart",
        "trendline <trendtype><period>(field) [AS newfield]",
        "iplocation",
        "city", "country", "region", "latitude", "longitude",
        "Data must include latitude and longitude values",
        "globallimit", "locallimit",
        "geostats",
        "geom",
        "addtotals",
        "create a column that contains numeric totals for each row",
        "create a row that contains numeric totals for each column",
        "What field the label should be placed in (in general, this should be the leftmost and first field)",
        "perform calculations, convert, round and format values, use conditional statements",
        "eval",
        "+",
        "round",
        "By adding characters to the field values",
        "comma",
        "Rest of the World",
        "like",
        "To replace null values in fields. Default replacement value is 0.",
        "A transaction is any group of related events that span time",
        "transaction field-list. field-list argument is a list of one or multiple fields.",
        "duration - difference between timestamp of first and last event in the transaction",
        "Defines the maximum total time between the earliest and latest events",
        "Specify maximum total time between events.",
        "The first event in this transaction includes the action 'addtocart', the last include the action 'purchase'",
        "1000",
        "Faster and more efficient",
        "When you need to see events correlated together, and/or must define event grouping based on start/end values or segments on time",
        "by configuring max_events_per_bucket in limits.conf",
        "Knowledge objects are tools you use to discover and analyze various aspects of your data",
        "A methodology for normalizing data, easily correlate data from different sources and source type.",
        "host, source and sourcetype",
        "_time and _raw",
        "search time",
        "Regex and delimiter",
        "field aliases",
        "Shortcut for performing repetitive, long, or complex transformations using the eval command",
        "Must be based on an extracted field",
        "Tags",
        "tag=<tag name>",
        "tag::<field> = <tagname>",
        "Settings->Tags-> List by field value pair",
        "Event types",
        "eventtype=<eventtype_name>",
        "Search string, Field values, tags",
        "macros",
        "Settings->Advanced search-> Search macros",
        "`macro`",
        "An expression for each argument to the macro can be made, with a corresponding error message, to ensure that the macro is being used correctly",
        "What happens if an event fits in multiple eventtypes?",
        "Priority decides which event takes precedence in the display order",
        "At execution time",
        "A search workflow action uses field values to perform a secondary search",
        "A POST workflow action sends field values to an external resource",
        "A GET workflow action retrieves information from an external resource",
        "Settings-> Fields-> Workflow actions-> New workflow action",
        "It's essentially a subset of data based on a data model",
        "Hierarchically structured datasets that generate searches and drive pivots",
        "Events, searches and transactions",
        "Constraints are essentially the search broken down into a hierarchy",
        "String", "Number", "Boolean", "IPV4",
        "Optional", "required", "Hidden", "Hidden & required",
        "Only events that contain this field are returned in Pivot",
        "Buttercup_Games_Site_Activity",
        "failed_request",
        "count(failed_request)",
        "Based on Users, or owner, app or all apps",
        "By uploading/download via the Splunk Web interface",
        "By creating summaries defined in time-series index files (tsidx) that have been optimized for speed",
        "The Splunk Common Information Model provides a methodology to normalize data",
        "Easier and more efficient correlation of data from different sources and source types",
        "Set of 22 pre-configured data models, fields and event category tags, least common denominator of a domain of interest",
        "True/false: The data models included in the CIM add-on are configured with data model acceleration turned off.",
        "By going to settings-> Data models, and identify a data model relevant to your dataset",
        "Creating new event types, tags, field aliases and field extractions",
        "By using the datamodel command and search against a specified data model object to see that the extracted field exists in the data model",
        "True/false: data model name and dataset name are case sensitive",
        "Email",
        "Retrieves data from a data model or named dataset",
        "Datamodel returns all fields prepended with data model name, from datamodel returns specified fields only",
        "True/false: 'from' command can also retrieve data from saved searches, reports or lookup files",
        "Difference between timestamp of first and last event in the transaction",
        "True/False: Data models from CIM search across all indexes by default"
    ]
    choices = set([correct_answer])
    while len(choices) < 4:
        choice = random.choice(pool)
        choices.add(choice)
    return list(choices)
def log_question(question, correct, filename):
    with open(filename, 'a') as file:
        file.write(f"Question: {question}\n")
        file.write(f"Answer: {correct}\n\n")

def ask_question(question, correct_answer):
    choices = generate_choices(correct_answer)
    random.shuffle(choices)
    
    print(f"Question: {question}")
    for i, choice in enumerate(choices, 1):
        print(f"{i}. {choice}")
    
    user_answer = input("Your answer (enter the number): ")
    
    try:
        if choices[int(user_answer) - 1] == correct_answer:
            print("Correct!")
            log_question(question, correct_answer, "correct_answers.txt")
        else:
            print(f"Incorrect. The correct answer is: {correct_answer}")
            log_question(question, correct_answer, "incorrect_answers.txt")
    except (IndexError, ValueError):
        print(f"Invalid choice. The correct answer is: {correct_answer}")
        log_question(question, correct_answer, "incorrect_answers.txt")

def main():
    random.shuffle(qa_pairs)
    for question, correct_answer in qa_pairs:
        ask_question(question, correct_answer)
        print()

if __name__ == "__main__":
    main()